#!/usr/bin/env python3
"""Generate a Flask proxy from analysis_result.json.

Supports both v2.0 (dataBody/dataHeaders) and v2.1 (transforms-driven) modes.
All transforms go through JSRPC — no crypto implementation in this file.

Usage:
  python3 scripts/emit_flask_proxy.py --analysis analysis_result.json --output generated/flask_proxy.py
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from common import load_json


def python_literal(value: Any) -> str:
    """Render a Python literal for embedding in generated code."""
    if value is True:
        return "True"
    if value is False:
        return "False"
    if value is None:
        return "None"
    if isinstance(value, dict):
        return "{" + ", ".join(
            f"{json.dumps(str(k), ensure_ascii=False)}: {python_literal(v)}"
            for k, v in value.items()
        ) + "}"
    if isinstance(value, list):
        return "[" + ", ".join(python_literal(v) for v in value) + "]"
    return json.dumps(value, ensure_ascii=False)


def normalize(analysis: dict) -> dict:
    """Normalize analysis to a common config format."""
    transforms = list(analysis.get("transforms") or [])
    if not transforms:
        # v2.0 mode: build transforms from parameters
        for name, config in (analysis.get("parameters") or {}).items():
            entrypoint = config.get("entrypoint", {}) if isinstance(config, dict) else {}
            transforms.append({
                "id": name,
                "direction": "request",
                "location": "body",
                "content_type": "auto",
                "path": f"$.{name}",
                "action": name,
                "candidate_path": entrypoint.get("path", ""),
                "safe_to_invoke": False,
            })

    jsrpc = dict(analysis.get("jsrpc") or {})
    transport = jsrpc.get("transport") if isinstance(jsrpc.get("transport"), dict) else {}
    jsrpc_config = {
        "base_url": jsrpc.get("base_url") or transport.get("go_url") or "http://127.0.0.1:12080",
        "group": jsrpc.get("group", "jsra"),
        "action": jsrpc.get("action_name") or jsrpc.get("action") or "",
        "transport": transport.get("type") or jsrpc.get("transport_type") or "legacy_get",
        "timeout_seconds": float(jsrpc.get("timeout_seconds", transport.get("timeout_seconds", 10))),
    }
    if not jsrpc_config["action"]:
        actions = [t.get("action") for t in transforms if t.get("action")]
        jsrpc_config["action"] = actions[0] if actions else "jsra_transform"

    flask = dict(analysis.get("flask") or {})
    flask_server = dict(analysis.get("flask_server") or {})
    return {
        "version": str(analysis.get("version", "2.1.0")),
        "jsrpc": jsrpc_config,
        "transforms": transforms,
        "flask_port": int(flask_server.get("port", flask.get("port", flask.get("listen_port", 5000)))),
        "flask_host": flask_server.get("host", flask.get("listen_host", "127.0.0.1")),
        "route": flask.get("route", "/autodecoder"),
    }


def build_script(analysis: dict) -> str:
    config = normalize(analysis)
    return f'''#!/usr/bin/env python3
# Generated by emit_flask_proxy.py. JSRPC is the only transform engine.
from __future__ import annotations

import json
from collections import OrderedDict
from urllib.parse import parse_qsl, urlencode

import requests
from flask import Flask, Response, jsonify, request

CONFIG = {python_literal(config)}
app = Flask(__name__)


class JSRPCError(Exception):
    def __init__(self, message: str, status: str = "error", detail: str = ""):
        super().__init__(message)
        self.status = status
        self.detail = detail


def _error_detail(payload: object) -> str:
    try:
        return json.dumps(payload, ensure_ascii=False)
    except (TypeError, ValueError):
        return str(payload)


def _extract_result(payload: object) -> object:
    if not isinstance(payload, dict):
        raise JSRPCError("JSRPC response must be a JSON object", "unexpected_response", _error_detail(payload))
    if payload.get("ok") is False or payload.get("status") in {{"error", "failed", "failure"}}:
        raise JSRPCError("JSRPC reported an error", "entrypoint_error", _error_detail(payload))
    for key in ("response_data", "data", "result", "value"):
        if key in payload:
            value = payload[key]
            if isinstance(value, dict) and value.get("ok") is False:
                raise JSRPCError("page function reported an error", "entrypoint_error", _error_detail(value))
            if isinstance(value, dict) and "result" in value and len(value) <= 3:
                value = value["result"]
            return value
    raise JSRPCError("JSRPC response has no result field", "unexpected_response", _error_detail(payload))


def _validate_result(value: object, input_value: object, transform: dict) -> object:
    if value is None or value == "":
        raise JSRPCError("page function returned an empty result", "invalid_result")
    if isinstance(value, str) and value.startswith("__JSRPC_ERROR__:"):
        raise JSRPCError(value, "entrypoint_error", value)
    if isinstance(value, dict):
        if value.get("error") or value.get("__JSRA_ERROR__"):
            raise JSRPCError("page function returned an error object", "entrypoint_error", _error_detail(value))
    if transform.get("reject_identity") and value == input_value:
        raise JSRPCError("page function returned the input unchanged", "invalid_result")
    return value


def jsrpc_call(action: str, value: object, transform: dict) -> object:
    cfg = CONFIG["jsrpc"]
    base = str(cfg["base_url"]).rstrip("/")
    timeout = float(cfg.get("timeout_seconds", 10))
    context = {{"transform_id": transform.get("id"), "candidate_path": transform.get("candidate_path")}}
    param = json.dumps({{"parameter": transform.get("id"), "value": value, "context": context}}, ensure_ascii=False)
    try:
        if cfg.get("transport") == "post_json":
            response = requests.post(base + "/go", json={{"group": cfg["group"], "action": action, "param": param}}, timeout=timeout)
        else:
            response = requests.get(base + "/go", params={{"group": cfg["group"], "action": action, "param": param}}, timeout=timeout)
        response.raise_for_status()
        try:
            payload = response.json()
        except ValueError as error:
            raise JSRPCError("JSRPC returned non-JSON data", "unexpected_response", str(error)) from error
        return _validate_result(_extract_result(payload), value, transform)
    except JSRPCError:
        raise
    except requests.Timeout as error:
        raise JSRPCError("JSRPC request timed out", "timeout", str(error)) from error
    except requests.RequestException as error:
        raise JSRPCError("JSRPC server is unavailable", "connection_error", str(error)) from error
    except Exception as error:
        raise JSRPCError("JSRPC call failed", "unknown", str(error)) from error


def json_get(data: object, path: str) -> object:
    if path in ("", "$", None):
        return data
    current = data
    for part in str(path).removeprefix("$.").split("."):
        if isinstance(current, list):
            current = current[int(part)]
        elif isinstance(current, dict):
            current = current[part]
        else:
            raise KeyError(path)
    return current


def json_set(data: object, path: str, value: object) -> object:
    if path in ("", "$", None):
        return value
    parts = str(path).removeprefix("$.").split(".")
    current = data
    for part in parts[:-1]:
        if isinstance(current, list):
            current = current[int(part)]
        else:
            current = current.setdefault(part, {{}})
    if isinstance(current, list):
        current[int(parts[-1])] = value
    else:
        current[parts[-1]] = value
    return data


def body_transforms(direction: str) -> list[dict]:
    return [t for t in CONFIG["transforms"] if t.get("direction") == direction and t.get("location") in ("body", "response")]


def transform_json(raw: str, transforms: list[dict]) -> str:
    data = json.loads(raw or "null", object_pairs_hook=OrderedDict)
    for transform in transforms:
        old = json_get(data, transform.get("path"))
        data = json_set(data, transform.get("path"), jsrpc_call(transform.get("action", CONFIG["jsrpc"]["action"]), old, transform))
    return json.dumps(data, ensure_ascii=False, separators=(",", ":"))


def transform_form(raw: str, transforms: list[dict]) -> str:
    pairs = parse_qsl(raw, keep_blank_values=True, strict_parsing=False)
    for transform in transforms:
        key = str(transform.get("path", "")).removeprefix("$.")
        pairs = [
            (name, jsrpc_call(transform.get("action", CONFIG["jsrpc"]["action"]), value, transform) if name == key else value)
            for name, value in pairs
        ]
    return urlencode(pairs, doseq=True)


def apply_body(raw: str, content_type: str, transforms: list[dict]) -> str:
    if not transforms:
        return raw
    mode = transforms[0].get("content_type", "auto")
    if mode == "json" or (mode == "auto" and "json" in content_type.lower()):
        return transform_json(raw, transforms)
    if mode == "form" or (mode == "auto" and "application/x-www-form-urlencoded" in content_type.lower()):
        return transform_form(raw, transforms)
    if mode == "raw":
        result = raw
        for transform in transforms:
            result = str(jsrpc_call(transform.get("action", CONFIG["jsrpc"]["action"]), result, transform))
        return result
    raise ValueError("Unsupported content type: " + content_type)


@app.get("/health")
def health():
    return jsonify({{"status": "ok", "version": CONFIG["version"], "jsrpc": CONFIG["jsrpc"]["base_url"]}})


@app.get("/healthz")
def healthz():
    return health()


@app.post("/transform")
def transform_endpoint():
    payload = request.get_json(force=True, silent=False)
    direction = payload.get("direction", "request")
    try:
        transforms = [t for t in CONFIG["transforms"] if t.get("direction") == direction]
        return jsonify({{"ok": True, "body": apply_body(payload.get("body", ""), payload.get("content_type", "application/octet-stream"), transforms)}})
    except JSRPCError as error:
        return jsonify({{"ok": False, "error": str(error), "status": error.status, "detail": error.detail}}), 502
    except Exception as error:
        return jsonify({{"ok": False, "error": str(error)}}), 400


@app.post(CONFIG["route"])
def autodecoder():
    raw = request.get_data(as_text=True)
    direction = request.args.get("direction", "request")
    content_type = request.headers.get("X-JSRA-Content-Type", request.content_type or "application/octet-stream")
    try:
        return Response(apply_body(raw, content_type, body_transforms(direction)), content_type="text/plain; charset=utf-8")
    except JSRPCError as error:
        return Response("JSRA_ERROR: " + str(error), status=502, content_type="text/plain; charset=utf-8")
    except Exception as error:
        return Response("JSRA_ERROR: " + str(error), status=400, content_type="text/plain; charset=utf-8")


if __name__ == "__main__":
    app.run(host=CONFIG["flask_host"], port=CONFIG["flask_port"], debug=False)
'''


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a strict JSRPC-only Flask proxy.")
    parser.add_argument("--analysis", required=True, help="Path to analysis_result.json.")
    parser.add_argument("--output", required=True, help="Output Python file path.")
    args = parser.parse_args()

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_script(load_json(args.analysis)), encoding="utf-8")
    print(json.dumps({"status": "ok", "output": str(output)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
